name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-deno:
    name: Test Deno
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Fmt Lint Deno Module
        run: deno fmt --check
      - name: Lint Deno Module
        run: deno lint
      - name: Check Deno Module
        shell: bash
        run: |
          deno check **/*.ts

  typos:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v3

      - name: Check spelling
        uses: crate-ci/typos@master
